# Generated by Django 5.0.5 on 2024-05-30 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuthGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
            ],
            options={
                "db_table": "auth_group",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthGroupPermissions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "db_table": "auth_group_permissions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codename", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "auth_permission",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("is_superuser", models.BooleanField()),
                ("username", models.CharField(max_length=150, unique=True)),
                ("last_name", models.CharField(max_length=150)),
                ("email", models.CharField(max_length=254)),
                ("is_staff", models.BooleanField()),
                ("is_active", models.BooleanField()),
                ("date_joined", models.DateTimeField()),
                ("first_name", models.CharField(max_length=150)),
            ],
            options={
                "db_table": "auth_user",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthUserGroups",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "db_table": "auth_user_groups",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthUserUserPermissions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "db_table": "auth_user_user_permissions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoAdminLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.TextField(blank=True, null=True)),
                ("object_repr", models.CharField(max_length=200)),
                ("action_flag", models.PositiveSmallIntegerField()),
                ("change_message", models.TextField()),
                ("action_time", models.DateTimeField()),
            ],
            options={
                "db_table": "django_admin_log",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoContentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("app_label", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "django_content_type",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoMigrations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("app", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("applied", models.DateTimeField()),
            ],
            options={
                "db_table": "django_migrations",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoSession",
            fields=[
                (
                    "session_key",
                    models.CharField(max_length=40, primary_key=True, serialize=False),
                ),
                ("session_data", models.TextField()),
                ("expire_date", models.DateTimeField()),
            ],
            options={
                "db_table": "django_session",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="LtecelltowerTpe",
            fields=[
                (
                    "_id",
                    models.AutoField(
                        db_column="_id", primary_key=True, serialize=False
                    ),
                ),
                ("radio", models.TextField()),
                ("mcc", models.IntegerField()),
                ("net", models.IntegerField()),
                ("area", models.IntegerField()),
                ("cell", models.IntegerField()),
                ("unit", models.IntegerField()),
                ("lon", models.FloatField()),
                ("lat", models.FloatField()),
                ("range", models.IntegerField()),
                ("samples", models.IntegerField()),
                ("changeable", models.IntegerField()),
                ("created", models.IntegerField()),
                ("updated", models.IntegerField()),
                ("averagesignal", models.IntegerField(db_column="averageSignal")),
            ],
            options={
                "db_table": "LTEcelltower_tpe",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TpeYb",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("station_no", models.CharField(max_length=20)),
                ("available_spaces", models.IntegerField()),
                ("isholiday", models.IntegerField()),
                ("rain_amt", models.FloatField()),
                ("updated_at", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "tpe_yb",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="YbCnty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(max_length=50)),
                ("area_code", models.CharField(max_length=10)),
                ("area_english", models.CharField(max_length=20)),
                ("bike_code", models.CharField(max_length=10)),
                ("station_start", models.IntegerField()),
                ("station_end", models.IntegerField()),
                ("domain", models.CharField(max_length=50)),
                ("is_open", models.IntegerField()),
                ("is_bind", models.IntegerField()),
                ("register_card", models.CharField(max_length=200)),
                ("contact_phone", models.CharField(max_length=200)),
                ("contact_mail", models.CharField(max_length=100)),
                ("ad_mail", models.CharField(max_length=100)),
                ("lat", models.CharField(max_length=20)),
                ("lng", models.CharField(max_length=20)),
                ("ride_count", models.IntegerField()),
                ("visit_count", models.IntegerField()),
                ("updated_at", models.CharField(max_length=20)),
                ("service_phone", models.CharField(max_length=20)),
                ("contact_phone_2", models.CharField(max_length=200)),
                ("ride_count2", models.IntegerField()),
                ("lat2", models.CharField(max_length=20)),
                ("lng2", models.CharField(max_length=20)),
                ("bike_type", models.CharField(max_length=20)),
                ("area_code_2", models.CharField(max_length=10)),
                ("area_name_tw", models.CharField(max_length=30)),
                ("area_name_en", models.CharField(max_length=30)),
            ],
            options={
                "db_table": "yb_cnty",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="YbStn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("area_code", models.CharField(max_length=10)),
                ("station_no", models.CharField(max_length=20)),
                ("name_tw", models.CharField(max_length=30)),
                ("district_tw", models.CharField(max_length=30)),
                ("address_tw", models.CharField(max_length=50)),
                ("name_en", models.CharField(max_length=30)),
                ("district_en", models.CharField(max_length=30)),
                ("address_en", models.CharField(max_length=50)),
                ("lat", models.CharField(max_length=20)),
                ("lng", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "yb_stn",
                "managed": False,
            },
        ),
    ]
