# Generated by Django 5.0.6 on 2024-06-12 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapAPP', '0002_tpe_yb_yb_cnty_yb_stn_yb_yb_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ltecelltowertpe',
            options={'managed': False},
        ),
    ]
