# Generated by Django 5.0.5 on 2024-06-13 13:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mapAPP", "0002_tpe_yb_yb_cnty_yb_stn_yb_yb_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="ltecelltowertpe",
            table="LTEcelltower_tpe_mapapp",
        ),
    ]
