# Generated by Django 5.0.6 on 2024-06-16 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapAPP', '0003_alter_ltecelltowertpe_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ltecelltowertpe',
            table='LtecelltowerTpe',
        ),
    ]
