# Generated by Django 5.0.6 on 2024-06-17 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapAPP', '0004_alter_ltecelltowertpe_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yb_stn2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_code', models.CharField(max_length=10)),
                ('station_no', models.CharField(max_length=20)),
                ('name_tw', models.CharField(max_length=30)),
                ('district_tw', models.CharField(max_length=30)),
                ('address_tw', models.CharField(max_length=50)),
                ('name_en', models.CharField(max_length=30)),
                ('district_en', models.CharField(max_length=30)),
                ('address_en', models.CharField(max_length=50)),
                ('lat', models.CharField(max_length=20)),
                ('lng', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Yb_stn2',
                'managed': False,
            },
        ),
    ]
