# Generated by Django 5.0.6 on 2024-06-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_user_id", models.CharField(max_length=50, unique=True)),
                ("display_name", models.CharField(max_length=100)),
                ("picture_url", models.URLField()),
            ],
        ),
    ]
