# Generated by Django 5.0.6 on 2024-06-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0002_userprofile_delete_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="line_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="password",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="telecom",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="username",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
