# Generated by Django 5.0.6 on 2024-06-21 11:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0002_userprofile_delete_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="access_token",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="bio",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="carrier",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="is_first_login",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="user",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="email",
            field=models.EmailField(
                default="default@example.com", max_length=100, unique=True
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="line_user_id",
            field=models.CharField(
                blank=True,
                default="default_line_user_id",
                max_length=100,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="password",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="telecom",
            field=models.CharField(
                blank=True, default="default_telecom_value", max_length=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="username",
            field=models.CharField(default="default_username", max_length=100),
        ),
    ]
