# Generated by Django 5.0.6 on 2024-06-08 13:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0002_alter_user_display_name_alter_user_line_user_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=100, unique=True)),
                ("access_token", models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
