# Generated by Django 5.0.6 on 2024-06-21 11:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0003_remove_userprofile_access_token_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="email",
            field=models.EmailField(default="default@example.com", max_length=100),
        ),
    ]
