# Generated by Django 5.0.6 on 2024-06-10 02:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0004_myuserprofile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="user_id",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="bio",
            field=models.TextField(default="This is my bio"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="user_temp",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="MyUserProfile",
        ),
    ]
