# Generated by Django 5.0.6 on 2024-06-23 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0004_remove_userprofile_access_token_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="line_id",
            new_name="line_user_id",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="first_name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
