# Generated by Django 5.0.6 on 2024-06-21 12:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0004_alter_userprofile_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="email",
            field=models.EmailField(
                default="default@example.com", max_length=100, unique=True
            ),
        ),
    ]
