# Generated by Django 5.0.6 on 2024-06-21 12:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0005_alter_userprofile_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="telecom",
            field=models.CharField(
                blank=True, default="default_telecom_value", max_length=50, null=True
            ),
        ),
    ]
