# Generated by Django 5.0.6 on 2024-06-24 09:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0005_rename_line_id_userprofile_line_user_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="first_name",
            new_name="line_name",
        ),
    ]
