# Generated by Django 5.0.6 on 2024-06-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0007_userprofile_last_login_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="user",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
    ]
