# Generated by Django 5.0.6 on 2024-06-21 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0009_alter_userprofile_telecom"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="first_name",
            field=models.CharField(default="default_first_name", max_length=100),
        ),
    ]
