# Generated by Django 5.0.6 on 2024-06-25 02:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0010_alter_userprofile_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="username",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
