# Generated by Django 5.0.6 on 2024-06-21 14:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0012_alter_userprofile_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="user",
        ),
    ]
