# Generated by Django 5.0.6 on 2024-06-21 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0014_alter_userprofile_email_alter_userprofile_first_name_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                default="default_user",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="email",
            field=models.EmailField(
                default="default_email", max_length=100, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="first_name",
            field=models.CharField(default="default_first_name", max_length=100),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="line_user_id",
            field=models.CharField(
                blank=True,
                default="default_line_user_id",
                max_length=100,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="password",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="telecom",
            field=models.CharField(
                blank=True, default="default_telecom", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="username",
            field=models.CharField(default="default_username", max_length=100),
        ),
    ]
