# Generated by Django 5.0.6 on 2024-06-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0017_alter_userprofile_email_alter_userprofile_first_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="user",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="user_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="username",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
