# Generated by Django 5.0.6 on 2024-06-21 15:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0018_remove_userprofile_user_userprofile_user_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="user_id",
        ),
    ]
