# Generated by Django 5.0.6 on 2024-06-07 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('start_time', models.BigIntegerField()),
                ('end_time', models.BigIntegerField()),
                ('wx', models.CharField(blank=True, max_length=50, null=True)),
                ('weather_code', models.CharField(blank=True, max_length=10, null=True)),
                ('pop_value', models.CharField(blank=True, max_length=10, null=True)),
                ('pop_unit', models.CharField(blank=True, max_length=10, null=True)),
                ('min_temp', models.CharField(blank=True, max_length=10, null=True)),
                ('max_temp', models.CharField(blank=True, max_length=10, null=True)),
                ('temp_unit', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
    ]
