# Generated by Django 5.0.6 on 2024-06-21 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Line_Official_Account_Bot', '0003_remove_lineusersessions_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineUserLocationsInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('timestamp', models.BigIntegerField()),
                ('address', models.CharField(max_length=1024)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        )
    ]
