# Generated by Django 5.0.6 on 2024-06-21 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Line_Official_Account_Bot', '0004_lineuserlocationsinformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineUserOnTimeBikeStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('available_spaces', models.CharField(max_length=10)),
                ('parking_spaces', models.CharField(max_length=10)),
                ('duration', models.CharField(max_length=10)),
                ('msg', models.CharField(max_length=50)),
                ('update_time', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'bike_status',
            },
        ),
    ]
